In [3]:
import pandas as pd

In [4]:
amazon_prime=pd.read_csv('./Datasets/amazon_prime_titles.csv')
amazon_prime

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,s9665,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,s9667,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."

In [5]:
# Elimino las columnas que no voy a usar
amazon_prime=amazon_prime.drop(columns=["country", "date_added","rating","description"])

In [6]:
# Consulto como quedo
amazon_prime.head()

,show_id,type,title,director,cast,release_year,duration,listed_in
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",2014,113 min,"Comedy, Drama"
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",2018,110 min,"Drama, International"
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",2017,74 min,"Action, Drama, Suspense"
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",2014,69 min,Documentary
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",1989,45 min,"Drama, Fantasy"

In [7]:
# Agrego una columna nueva para saber a que plataforma pertenece cada Movie o Serie.
amazon_prime['plataform'] = 'Amazon'

In [8]:
disney_plus=pd.read_csv('./Datasets/disney_plus_titles.csv')
disney_plus

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...
...,...,...,...,...,...,...,...,...,...,...,...,...
1445,s1446,Movie,X-Men Origins: Wolverine,Gavin Hood,"Hugh Jackman, Liev Schreiber, Danny Huston, wi...","United States, United Kingdom","June 4, 2021",2009,PG-13,108 min,"Action-Adventure, Family, Science Fiction",Wolverine unites with legendary X-Men to fight...
1446,s1447,Movie,Night at the Museum: Battle of the Smithsonian,Shawn Levy,"Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...","United States, Canada","April 2, 2021",2009,PG,106 min,"Action-Adventure, Comedy, Family",Larry Daley returns to rescue some old friends...
1447,s1448,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States","December 18, 2020",2016,PG-13,107 min,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum..."
1448,s1449,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States","September 18, 2020",2003,PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...
1449,s1450,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,"April 1, 2020",2012,TV-G,2 min,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.

In [9]:
# Elimino las columnas que no voy a usar
disney_plus=disney_plus.drop(columns=["country", "date_added","rating","description"])

In [10]:
# Consulto como quedo mi DF
disney_plus.head()

,show_id,type,title,director,cast,release_year,duration,listed_in
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",2016,23 min,"Animation, Family"
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",1988,91 min,Comedy
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",2011,23 min,"Animation, Comedy, Family"
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",2021,41 min,Musical
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",2021,1 Season,"Docuseries, Historical, Music"

In [11]:
# Agrego una columna nueva para saber a que plataforma pertenece cada Movie o Serie.
disney_plus['plataform'] = 'Disney'

In [12]:
hulu=pd.read_csv('./Datasets/hulu_titles.csv')
hulu

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,NaN,"October 24, 2021",2021,TV-MA,NaN,"Comedy, Stand Up",​Comedian Ricky Velez bares it all with his ho...
1,s2,Movie,Silent Night,NaN,NaN,NaN,"October 23, 2021",2020,NaN,94 min,"Crime, Drama, Thriller","Mark, a low end South London hitman recently r..."
2,s3,Movie,The Marksman,NaN,NaN,NaN,"October 23, 2021",2021,PG-13,108 min,"Action, Thriller",A hardened Arizona rancher tries to protect an...
3,s4,Movie,Gaia,NaN,NaN,NaN,"October 22, 2021",2021,R,97 min,Horror,A forest ranger and two survivalists with a cu...
4,s5,Movie,Settlers,NaN,NaN,NaN,"October 22, 2021",2021,NaN,104 min,"Science Fiction, Thriller",Mankind's earliest settlers on the Martian fro...
...,...,...,...,...,...,...,...,...,...,...,...,...
3068,s3069,TV Show,Star Trek: The Original Series,NaN,NaN,United States,NaN,1966,TV-PG,3 Seasons,"Action, Adventure, Classics",The 23rd century adventures of Captain James T...
3069,s3070,TV Show,Star Trek: Voyager,NaN,NaN,United States,NaN,1997,TV-PG,7 Seasons,"Action, Adventure, Science Fiction",Catapulted into the distant sector of the gala...
3070,s3071,TV Show,The Fades,NaN,NaN,United Kingdom,NaN,2011,TV-14,1 Season,"Horror, International, Science Fiction",Seventeen-year-old Paul is haunted by apocalyp...
3071,s3072,TV Show,The Twilight Zone,NaN,NaN,United States,NaN,1959,TV-PG,5 Seasons,"Classics, Science Fiction, Thriller",Rod Serling's seminal anthology series focused...
3072,s3073,TV Show,Tokyo Magnitude 8.0,NaN,NaN,Japan,NaN,2009,TV-14,1 Season,"Anime, Drama, International",The devastation is unleashed in the span of se...

In [13]:
# Elimino las columnas que no voy a usar
hulu=hulu.drop(columns=["country", "date_added","rating","description"])

In [14]:
# Consulto como quedo mi DF
hulu.head()

,show_id,type,title,director,cast,release_year,duration,listed_in
0,s1,Movie,Ricky Velez: Here's Everything,NaN,NaN,2021,NaN,"Comedy, Stand Up"
1,s2,Movie,Silent Night,NaN,NaN,2020,94 min,"Crime, Drama, Thriller"
2,s3,Movie,The Marksman,NaN,NaN,2021,108 min,"Action, Thriller"
3,s4,Movie,Gaia,NaN,NaN,2021,97 min,Horror
4,s5,Movie,Settlers,NaN,NaN,2021,104 min,"Science Fiction, Thriller"

In [15]:
# Agrego una columna nueva para saber a que plataforma pertenece cada Movie o Serie ya que despues voy a unificar los DF.
hulu['plataform'] = 'Hulu'

In [16]:
netflix=pd.read_json('./Datasets/netflix_titles.json')
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,None,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,None,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",None,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,None,None,None,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,None,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,None,None,None,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [17]:
# Elimino las columnas que no voy a usar
netflix=netflix.drop(columns=["country", "date_added","rating","description"])

In [18]:
netflix.head()

,show_id,type,title,director,cast,release_year,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,None,2020,90 min,Documentaries
1,s2,TV Show,Blood & Water,None,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",2021,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",2021,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,None,None,2021,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,None,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",2021,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."

In [19]:
# Agrego una columna nueva para saber a que plataforma pertenece cada Movie o Serie.
netflix['plataform'] = 'Netflix'

In [20]:
#Concateno los archivos en un solo DF
df_unificado= pd.concat([amazon_prime,disney_plus,hulu,netflix],ignore_index=True)

In [21]:
#Veo como me quedo el DF unificado.
df_unificado.head()

,show_id,type,title,director,cast,release_year,duration,listed_in,plataform
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",2014,113 min,"Comedy, Drama",Amazon
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",2018,110 min,"Drama, International",Amazon
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",2017,74 min,"Action, Drama, Suspense",Amazon
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",2014,69 min,Documentary,Amazon
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",1989,45 min,"Drama, Fantasy",Amazon

In [65]:
# Paso la tabla unificada a SQL para poder visualizarlas mejor y seguir normalizando los datos.
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:Na3638ty@localhost/peliculas')

df_unificado.to_sql('df_unificado',con=engine,index=False,if_exists='replace')

OperationalError: (pymysql.err.OperationalError) (1241, 'Operand should contain 1 column(s)')
[SQL: INSERT INTO df_unificado (`Indice`, `Tipo_Film`, `Titulo`, `Director`, `Ano_Rodaje`, `Duracion`, `Plataforma`, tiempo_duracion, medida_tiempo_duracion, `Reparto`, `Genero`) VALUES (%(Indice)s, %(Tipo_Film)s, %(Titulo)s, %(Director)s, %(Ano_Rodaje)s, %(Duracion)s, %(Plataforma)s, %(tiempo_duracion)s, %(medida_tiempo_duracion)s, %(Reparto)s, %(Genero)s)]
[parameters: ({'Indice': 0, 'Tipo_Film': 'Movie', 'Titulo': 'The Grand Seduction', 'Director': 'Don McKellar', 'Ano_Rodaje': 2014, 'Duracion': '113 min', 'Plataforma': 'Amazon', 'tiempo_duracion': 113.0, 'medida_tiempo_duracion': 'min', 'Reparto': ['Brendan Gleeson', ' Taylor Kitsch', ' Gordon Pinsent'], 'Genero': ['Comedy', ' Drama']}, {'Indice': 1, 'Tipo_Film': 'Movie', 'Titulo': 'Take Care Good Night', 'Director': 'Girish Joshi', 'Ano_Rodaje': 2018, 'Duracion': '110 min', 'Plataforma': 'Amazon', 'tiempo_duracion': 110.0, 'medida_tiempo_duracion': 'min', 'Reparto': ['Mahesh Manjrekar', ' Abhay Mahajan', ' Sachin Khedekar'], 'Genero': ['Drama', ' International']}, {'Indice': 2, 'Tipo_Film': 'Movie', 'Titulo': 'Secrets of Deception', 'Director': 'Josh Webber', 'Ano_Rodaje': 2017, 'Duracion': '74 min', 'Plataforma': 'Amazon', 'tiempo_duracion': 74.0, 'medida_tiempo_duracion': 'min', 'Reparto': ['Tom Sizemore', ' Lorenzo Lamas', ' Robert LaSardo', ' Richard Jones', ' Yancey Arias', ' Noel Gugliemi'], 'Genero': ['Action', ' Drama', ' Suspense']}, {'Indice': 3, 'Tipo_Film': 'Movie', 'Titulo': 'Pink: Staying True', 'Director': 'Sonia Anderson', 'Ano_Rodaje': 2014, 'Duracion': '69 min', 'Plataforma': 'Amazon', 'tiempo_duracion': 69.0, 'medida_tiempo_duracion': 'min', 'Reparto': ['Interviews with: Pink', ' Adele', ' Beyoncé', ' Britney Spears', ' Christina Aguilera', ' more!'], 'Genero': ['Documentary']}, {'Indice': 4, 'Tipo_Film': 'Movie', 'Titulo': 'Monster Maker', 'Director': 'Giles Foster', 'Ano_Rodaje': 1989, 'Duracion': '45 min', 'Plataforma': 'Amazon', 'tiempo_duracion': 45.0, 'medida_tiempo_duracion': 'min', 'Reparto': ['Harry Dean Stanton', " Kieran O'Brien", ' George Costigan', ' Amanda Dickinson', ' Alison Steadman', ' Grant Bardsley', ' Bill Moody', ' Matthew Scurfield'], 'Genero': ['Drama', ' Fantasy']}, {'Indice': 5, 'Tipo_Film': 'Movie', 'Titulo': 'Living With Dinosaurs', 'Director': 'Paul Weiland', 'Ano_Rodaje': 1989, 'Duracion': '52 min', 'Plataforma': 'Amazon', 'tiempo_duracion': 52.0, 'medida_tiempo_duracion': 'min', 'Reparto': ['Gregory Chisholm', ' Juliet Stevenson', ' Brian Henson', ' Michael Maloney'], 'Genero': ['Fantasy', ' Kids']}, {'Indice': 6, 'Tipo_Film': 'Movie', 'Titulo': 'Hired Gun', 'Director': 'Fran Strine', 'Ano_Rodaje': 2017, 'Duracion': '98 min', 'Plataforma': 'Amazon', 'tiempo_duracion': 98.0, 'medida_tiempo_duracion': 'min', 'Reparto': ['Alice Cooper', ' Liberty DeVitto', ' Ray Parker Jr.', ' David Foster', ' Jason Hook', ' Steve Vai', ' Phil X', ' Rudy Sarzo', ' Jay Graydon', ' Rob  ... (64 characters truncated) ...  ' Eva Gardner', ' John 5', ' Eric Singer', ' Derek St. Holmes', ' Paul Bushnell', ' Jason Newsted', ' Glen Sobel', ' Nita Strauss', ' Chris Johnson'], 'Genero': ['Documentary', ' Special Interest']}, {'Indice': 7, 'Tipo_Film': 'Movie', 'Titulo': 'Grease Live!', 'Director': 'Thomas Kail, Alex Rudzinski', 'Ano_Rodaje': 2016, 'Duracion': '131 min', 'Plataforma': 'Amazon', 'tiempo_duracion': 131.0, 'medida_tiempo_duracion': 'min', 'Reparto': ['Julianne Hough', ' Aaron Tveit', ' Vanessa Hudgens', ' Keke Palmer', ' Carly Rae Jepson', ' Mario Lopez', ' Carlos PenaVega', ' Kether Donohue', ' Jordan Fisher', ' David Del Rio', ' Andrew Call', ' Wendell Pierce', ' Boyz II Men', ' Jessie J', ' Ana Gasteyer', ' Didi Conn'], 'Genero': ['Comedy']}  ... displaying 10 of 22998 total bound parameter sets ...  {'Indice': 22996, 'Tipo_Film': 'Movie', 'Titulo': 'Zoom', 'Director': 'Peter Hewitt', 'Ano_Rodaje': 2006, 'Duracion': '88 min', 'Plataforma': 'Netflix', 'tiempo_duracion': 88.0, 'medida_tiempo_duracion': 'min', 'Reparto': ['Tim Allen', ' Courteney Cox', ' Chevy Chase', ' Kate Mara', ' Ryan Newman', ' Michael Cassidy', ' Spencer Breslin', ' Rip Torn', ' Kevin Zegers'], 'Genero': ['Children & Family Movies', ' Comedies']}, {'Indice': 22997, 'Tipo_Film': 'Movie', 'Titulo': 'Zubaan', 'Director': 'Mozez Singh', 'Ano_Rodaje': 2015, 'Duracion': '111 min', 'Plataforma': 'Netflix', 'tiempo_duracion': 111.0, 'medida_tiempo_duracion': 'min', 'Reparto': ['Vicky Kaushal', ' Sarah-Jane Dias', ' Raaghav Chanana', ' Manish Chaudhary', ' Meghna Malik', ' Malkeet Rauni', ' Anita Shabdish', ' Chittaranjan Tripathy'], 'Genero': ['Dramas', ' International Movies', ' Music & Musicals']})]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [23]:
# Cambiar el nombre de las columnas del DF unificado asi podemos identificar rápidamente el contenido.
df_unificado.rename(columns={'type':'Tipo_Film',
                        'title':'Titulo',
                        'director':'Director',
                        'cast':'Reparto',
                        'release_year':'Ano_Rodaje',
                        'duration':'Duracion',
                        'listed_in':'Genero',
                        'plataform':'Plataforma',},
               inplace=True)

In [24]:
# Rellenar los datos vacios con el objetivo de optimizar las consultas.
df_unificado['Duracion'].fillna(0, inplace=True)
df_unificado.fillna('Sin Dato', inplace=True)

In [25]:
# Se crea una columna con un indice nuevo ya que la columna show_id	tiene datos repetidos
df_unificado['Indice'] = df_unificado.index
df_unificado = df_unificado[['Indice','Tipo_Film','Titulo','Director','Reparto','Ano_Rodaje','Duracion','Genero','Plataforma',]]

In [26]:
# Con esto partimos la columna 'Duracion' en dos para separar los datos enteros de los string.
df_dur=df_unificado["Duracion"].str.split(expand=True) #Se crea un dataframe con los datos de la columna "Duracion" separando el número de la unidad
df_unificado['tiempo_duracion']=df_dur[0]
df_unificado['medida_tiempo_duracion']=df_dur[1]

In [27]:
df_unificado['tiempo_duracion'] = df_unificado['tiempo_duracion'].astype('float64') # cambie tipo de dato de la columna porque no me dejaba sacar la mean ya que estaba en int

In [28]:
# Se calcula el promedios de duración de películas o series por Plataforma
prom_movies = {}
prom_series = {}
for Plataforma in df_unificado['Plataforma'].unique():
    prom_movies[Plataforma] = round(df_unificado[(df_unificado['tiempo_duracion'] !=0 ) & (df_unificado['Tipo_Film']=='Movie')&(df_unificado['Plataforma']==Plataforma)]['tiempo_duracion'].mean()) #Se halla la media de la duración de películas por plataforma
    prom_series[Plataforma] = round(df_unificado[(df_unificado['tiempo_duracion'] !=0 ) & (df_unificado['Tipo_Film']=='TV Show') & (df_unificado['Plataforma']==Plataforma)]['tiempo_duracion'].mean()) #Se halla la media de la duración de series por plataforma
    df_unificado['tiempo_duracion'][df_unificado['tiempo_duracion'].loc[(df_unificado['tiempo_duracion'] == 0) & (df_unificado['Tipo_Film']=='Movie') & (df_unificado['Plataforma']==Plataforma)].index]=prom_movies[Plataforma]
    df_unificado['tiempo_duracion'][df_unificado['tiempo_duracion'].loc[(df_unificado['tiempo_duracion'] == 0) & (df_unificado['Tipo_Film']=='TV Show') & (df_unificado['Plataforma']==Plataforma)].index]=prom_series[Plataforma]
print(prom_movies, prom_series)

{'Amazon': 91, 'Disney': 72, 'Hulu': 98, 'Netflix': 100} {'Amazon': 2, 'Disney': 2, 'Hulu': 3, 'Netflix': 2}

C:\Users\Natalia\AppData\Local\Temp\ipykernel_5452\2546040850.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unificado['tiempo_duracion'][df_unificado['tiempo_duracion'].loc[(df_unificado['tiempo_duracion'] == 0) & (df_unificado['Tipo_Film']=='Movie') & (df_unificado['Plataforma']==Plataforma)].index]=prom_movies[Plataforma]
C:\Users\Natalia\AppData\Local\Temp\ipykernel_5452\2546040850.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unificado['tiempo_duracion'][df_unificado['tiempo_duracion'].loc[(df_unificado['tiempo_duracion'] == 0) & (df_unificado['Tipo_Film']=='TV Show') & (df_unificado['Plataforma']==Plataforma)].index]=prom_series[Plataforma]
C:\Users\Natalia\AppData\Local\Temp\ipykernel_5452\2546040850.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unificado['tiempo_duracion'][df_unificado['tiempo_duracion'].loc[(df_unificado['tiempo_duracion'] == 0) & (df_unificado['Tipo_Film']=='Movie') & (df_unificado['Plataforma']==Plataforma)].index]=prom_movies[Plataforma]
C:\Users\Natalia\AppData\Local\Temp\ipykernel_5452\2546040850.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unificado['tiempo_duracion'][df_unificado['tiempo_duracion'].loc[(df_unificado['tiempo_duracion'] == 0) & (df_unificado['Tipo_Film']=='TV Show') & (df_unificado['Plataforma']==Plataforma)].index]=prom_series[Plataforma]
C:\Users\Natalia\AppData\Local\Temp\ipykernel_5452\2546040850.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unificado['tiempo_duracion'][df_unificado['tiempo_duracion'].loc[(df_unificado['tiempo_duracion'] == 0) & (df_unificado['Tipo_Film']=='Movie') & (df_unificado['Plataforma']==Plataforma)].index]=prom_movies[Plataforma]
C:\Users\Natalia\AppData\Local\Temp\ipykernel_5452\2546040850.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unificado['tiempo_duracion'][df_unificado['tiempo_duracion'].loc[(df_unificado['tiempo_duracion'] == 0) & (df_unificado['Tipo_Film']=='TV Show') & (df_unificado['Plataforma']==Plataforma)].index]=prom_series[Plataforma]
C:\Users\Natalia\AppData\Local\Temp\ipykernel_5452\2546040850.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unificado['tiempo_duracion'][df_unificado['tiempo_duracion'].loc[(df_unificado['tiempo_duracion'] == 0) & (df_unificado['Tipo_Film']=='Movie') & (df_unificado['Plataforma']==Plataforma)].index]=prom_movies[Plataforma]
C:\Users\Natalia\AppData\Local\Temp\ipykernel_5452\2546040850.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unificado['tiempo_duracion'][df_unificado['tiempo_duracion'].loc[(df_unificado['tiempo_duracion'] == 0) & (df_unificado['Tipo_Film']=='TV Show') & (df_unificado['Plataforma']==Plataforma)].index]=prom_series[Plataforma]

In [29]:
df_unificado.iloc[788]

Indice                                                             788
Tipo_Film                                                        Movie
Titulo                    Testing title - Parichey is using this title
Director                                                        Tester
Reparto                                                          Test1
Ano_Rodaje                                                        2020
Duracion                                                         0 min
Genero                                                          Action
Plataforma                                                      Amazon
tiempo_duracion                                                   91.0
medida_tiempo_duracion                                             min
Name: 788, dtype: object

In [30]:
#Se convierten los actores en listas dentro del dataframe
df_unificado['Reparto_1'] = df_unificado['Reparto'].str.split("," or ":")
df_unificado.drop(columns=['Reparto'],inplace=True)
df_unificado.rename(columns={'Reparto_1':'Reparto'},inplace=True)

In [135]:
#Creación de DataFrame para los actores
dic_actores = {'actor':[],
                'año':[],
                'plataforma':[]} #Se crea un diccionario para luego ser convertido en dataframe
for index, actors in enumerate(df_unificado['Reparto']):
    for actor in actors:
        dic_actores['actor'].append(actor) #Se agrega el actor al diccionario
        dic_actores['año'].append(df_unificado['Ano_Rodaje'][index]) #Se agrega el año correspondiente actor al diccionario
        dic_actores['plataforma'].append(df_unificado['Plataforma'][index]) #Se agrega la plataforma correspondiente al actor al diccionario
df_actores = pd.DataFrame(dic_actores)
#df_actors=df_actors.drop_duplicates().reset_index()

In [145]:
df_unificado['Genero_1'] = df_unificado["Genero"].str.split(",")
df_unificado.drop(columns=['Genero'],inplace=True)
df_unificado.rename(columns={'Genero_1':'Genero'}, inplace=True)

In [34]:
#Creación de DataFrame para los generos
dic_genero = {'genero':[],
                'plataforma':[]} #Se crea un diccionario para luego ser convertido en dataframe
for index, generos in enumerate(df_unificado['Genero']):
    for genero in generos:
        dic_genero['genero'].append(genero) #Se agrega el genero al diccionario
        dic_genero['plataforma'].append(df_unificado['Plataforma'][index])
df_genero = pd.DataFrame(dic_genero)

In [136]:
df_actores.to_csv('actores.csv')
df_genero.to_csv('generos.csv')
df_unificado.to_csv('general.csv')

In [45]:
df_unificado.head()

,Indice,Tipo_Film,Titulo,Director,Ano_Rodaje,Duracion,Plataforma,tiempo_duracion,medida_tiempo_duracion,Reparto,Genero
0,0,Movie,The Grand Seduction,Don McKellar,2014,113 min,Amazon,113.0,min,"[Brendan Gleeson, Taylor Kitsch, Gordon Pins...","[Comedy, Drama]"
1,1,Movie,Take Care Good Night,Girish Joshi,2018,110 min,Amazon,110.0,min,"[Mahesh Manjrekar, Abhay Mahajan, Sachin Khe...","[Drama, International]"
2,2,Movie,Secrets of Deception,Josh Webber,2017,74 min,Amazon,74.0,min,"[Tom Sizemore, Lorenzo Lamas, Robert LaSardo...","[Action, Drama, Suspense]"
3,3,Movie,Pink: Staying True,Sonia Anderson,2014,69 min,Amazon,69.0,min,"[Interviews with: Pink, Adele, Beyoncé, Bri...",[Documentary]
4,4,Movie,Monster Maker,Giles Foster,1989,45 min,Amazon,45.0,min,"[Harry Dean Stanton, Kieran O'Brien, George ...","[Drama, Fantasy]"

In [32]:
pip freeze

anyio==3.6.2Note: you may need to restart the kernel to use updated packages.

asttokens==2.0.5
backcall==0.2.0
beautifulsoup4==4.11.1
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.5
contourpy==1.0.5
cycler==0.11.0
debugpy==1.6.2
decorator==5.1.1
entrypoints==0.4
et-xmlfile==1.1.0
executing==0.9.1
fastapi==0.88.0
fonttools==4.37.3
greenlet==2.0.1
h11==0.14.0
idna==3.4
ipykernel==6.15.1
ipython==8.4.0
jedi==0.18.1
joblib==1.2.0
jupyter-client==7.3.4
jupyter-core==4.11.1
kiwisolver==1.4.4
kneed==0.8.1
matplotlib==3.6.0
matplotlib-inline==0.1.3
nest-asyncio==1.5.5
numpy==1.23.3
openpyxl==3.0.10
packaging==21.3
pandas==1.4.4
parso==0.8.3
pickleshare==0.7.5
Pillow==9.2.0
prompt-toolkit==3.0.30
psutil==5.9.1
pure-eval==0.2.2
pydantic==1.10.2
Pygments==2.12.0
PyMySQL==1.0.2
pyparsing==3.0.9
python-dateutil==2.8.2
python-multipart==0.0.5
pytz==2022.2.1
pywin32==304
pyzmq==23.2.0
requests==2.28.1
scikit-learn==1.1.3
scipy==1.9.3
seaborn==0.12.1
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
SQLAlchemy==1.4.44
stack-data==0.3.0
starlette==0.22.0
threadpoolctl==3.1.0
tornado==6.2
traitlets==5.3.0
typing==3.7.4.3
typing_extensions==4.4.0
urllib3==1.26.12
uvicorn==0.20.0
wcwidth==0.2.5

In [68]:
df_unificado

,Indice,Tipo_Film,Titulo,Director,Ano_Rodaje,Duracion,Plataforma,tiempo_duracion,medida_tiempo_duracion,Reparto,Genero
0,0,Movie,The Grand Seduction,Don McKellar,2014,113 min,Amazon,113.0,min,"[Brendan Gleeson, Taylor Kitsch, Gordon Pins...","[Comedy, Drama]"
1,1,Movie,Take Care Good Night,Girish Joshi,2018,110 min,Amazon,110.0,min,"[Mahesh Manjrekar, Abhay Mahajan, Sachin Khe...","[Drama, International]"
2,2,Movie,Secrets of Deception,Josh Webber,2017,74 min,Amazon,74.0,min,"[Tom Sizemore, Lorenzo Lamas, Robert LaSardo...","[Action, Drama, Suspense]"
3,3,Movie,Pink: Staying True,Sonia Anderson,2014,69 min,Amazon,69.0,min,"[Interviews with: Pink, Adele, Beyoncé, Bri...",[Documentary]
4,4,Movie,Monster Maker,Giles Foster,1989,45 min,Amazon,45.0,min,"[Harry Dean Stanton, Kieran O'Brien, George ...","[Drama, Fantasy]"
...,...,...,...,...,...,...,...,...,...,...,...
22993,22993,Movie,Zodiac,David Fincher,2007,158 min,Netflix,158.0,min,"[Mark Ruffalo, Jake Gyllenhaal, Robert Downe...","[Cult Movies, Dramas, Thrillers]"
22994,22994,TV Show,Zombie Dumb,Sin Dato,2018,2 Seasons,Netflix,2.0,Seasons,[Sin Dato],"[Kids' TV, Korean TV Shows, TV Comedies]"
22995,22995,Movie,Zombieland,Ruben Fleischer,2009,88 min,Netflix,88.0,min,"[Jesse Eisenberg, Woody Harrelson, Emma Ston...","[Comedies, Horror Movies]"
22996,22996,Movie,Zoom,Peter Hewitt,2006,88 min,Netflix,88.0,min,"[Tim Allen, Courteney Cox, Chevy Chase, Kat...","[Children & Family Movies, Comedies]"
22997,22997,Movie,Zubaan,Mozez Singh,2015,111 min,Netflix,111.0,min,"[Vicky Kaushal, Sarah-Jane Dias, Raaghav Cha...","[Dramas, International Movies, Music & Music..."

In [50]:
#Función 1
def get_max_duration(Ano_Rodaje, Plataforma, Tipo_Film):
    message = f"Máximo de {Plataforma} es"
    return {message:df_unificado[(df_unificado['Ano_Rodaje']==Ano_Rodaje)&(df_unificado['Plataforma']==Plataforma)&(df_unificado['medida_tiempo_duracion']== Tipo_Film)]['tiempo_duracion'].max()}

In [82]:
get_max_duration(2018,'Hulu','min')

{'Máximo de Hulu es': 151.0}

In [107]:
#Función 2
def get_count_plataform(plataforma):   
    return{f"Cantidad de películas en {plataforma} es":df_unificado[(df_unificado['Plataforma']==plataforma)&(df_unificado['Tipo_Film']=='movie')]['Tipo_Film'].count().tolist(),
    f"Cantidad de series en {plataforma} es":df_unificado[(df_unificado['Plataforma']==plataforma)&(df_unificado['Tipo_Film']=='tv show')]['Tipo_Film'].count().tolist()}

In [108]:
get_count_plataform('Netflix')

{'Cantidad de películas en Netflix es': 0,
 'Cantidad de series en Netflix es': 0}

In [116]:
#Función 3
def get_listedin(genero):
    list_genero = []
    for plataforma in df_unificado['Plataforma'].unique():
        list_genero.append(df_genero[(df_genero['genero']==genero)&(df_genero['plataforma']==plataforma)].shape[0])
    
    maximo = max(list_genero)
    if list_genero.index(maximo)==0:
        return {'Amazon': maximo}
    elif list_genero.index(maximo)==1:
        return {'Disney': maximo}
    elif list_genero.index(maximo)==2:
        return {'Hulu': maximo}
    elif list_genero.index('Netflix',maximo)==2:
        return {'Netflix': maximo}

In [161]:
#Función 3
def get_listedin(genero):
    genero={(df_genero[(df_genero['genero']==genero)]['plataforma'].value_counts().idxmax()):
    (df_genero[(df_genero['genero']==genero)]['plataforma'].value_counts().max().tolist())}
    return genero

In [163]:
get_listedin('Dramas')

{'Netflix': 1600}

In [150]:
df1=df_genero[(df_genero['genero']=='Drama')]['plataforma'].value_counts()
df1

Amazon    2216
Hulu       415
Disney      27
Name: plataforma, dtype: int64

In [117]:
get_listedin('Drama')

{'Amazon': 2216}

In [146]:
#Función 4
def get_actor(plataforma:str, año:int):
    data = df_actores[(df_actores['año']==año)&(df_actores['plataforma']==plataforma)]['actor']
    # return {data.value_counts().max()}
    if data.value_counts().index[0] == 'sin dato':
        return {data.value_counts().index[1]:data.value_counts()[1].tolist()}
    elif data.value_counts().index[0] != 'sin dato':
        return {data.value_counts().index[0]:data.value_counts()[0].tolist()}

In [147]:
get_actor('netflix', 2010)

IndexError: index 0 is out of bounds for axis 0 with size 0